---
framework: jest                  # Mention the testing framework mocha or jest
postMerge:
    pattern:
    - "./test/**/*.test.ts"            # Glob pattern to path where tests that should run post-merge are written
preMerge:
    pattern:
    - "./test/**/*.test.ts"              # Glob pattern to path where tests that should run pre-merge are written
preRun:
    - yarn install                   # Mention pre-run steps here
postRun:
    - yarn --version                # Mention post-run steps here
version: 2.0